<?php
$this->title = "Delete examination";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->examination['idexaminations']); ?>' 
'<?php echo $this->escape($this->examination['courses_idcourses']); ?>'
'<?php echo $this->escape($this->examination['exams_idexams']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->examination['idexaminations']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>