<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
     <h1>Tequila Tool</h1>
     <p>Do you think you deserve a Tequila???... Take the examinations here to see if you really know PHP</p>
     <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
     <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
</div>