<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
     <h1>Tequila Tool</h1>
     <p>Hello, can I help You?
     
     <p>
     	<form class="form-signin">
	        <h2 class="form-signin-heading">Please sign in</h2>
	        <input type="text" class="input-block-level" placeholder="Email address">
	        <input type="password" class="input-block-level" placeholder="Password">
	        <label class="checkbox">
	          <input type="checkbox" value="remember-me"> Remember me
	        </label>
	        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
      	</form>
      </p>
</div>