<?php
//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
//echo $this->doctype(); 
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="/assets/ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Tequila Tool</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/exam">Exams</a></li>
                  <li><a href="/user">Users</a></li>
                  <li><a href="/courses">Courses</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      
      <?php echo $this->layout()->content; ?>
        	<?php echo $this->escape($this->title); ?>
        	
      <!-- Example row of columns -->
      <div class="row">
       		<div class="span4">
              <h2>Alumns</h2>
              <p>You can create alumns by adding them to the data repository in a very simple way: email, name, birth date. </p>
            </div><!--/span-->
            <div class="span4">
              <h2>Courses</h2>
              <p>Create your course and add alumns. Really simple.</p>              
            </div><!--/span-->
            <div class="span4">
              <h2>Exams</h2>
              <p>Create your exam with some questions types and at most five possible answers.</p>              
            </div><!--/span-->
      </div>
		
	  <div class="row">
       		<div class="span4">
              <h2>Examinate a course</h2>
              <p>Here we are. Examin your course. The alumns will receive an email with the link to take the examination.</p>
            </div><!--/span-->
            <div class="span4">
              <h2>Report alumns</h2>
              <p>And then you can send them the correction. Besides, you store the information for future analysis. </p>
              <p><a class="btn btn-success" href="#">Give as some help so we could develop it</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Enjoy Tequilas!!!</h2>
              <p>Free, opensource, and proudly made with Zend Framework. Yes, PHP and MySQL, Twitter bootstrap and jquery. </p>
              <p>Also, the developers are students from some courses of PHP made by the project leader. </p>
			  <!-- <p><a class="btn" href="#">View details &raquo;</a></p> -->
            </div><!--/span-->
      </div>
		
      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/assets/js/jquery.js"></script>
    <script src="/assets/js/bootstrap-transition.js"></script>
    <script src="/assets/js/bootstrap-alert.js"></script>
    <script src="/assets/js/bootstrap-modal.js"></script>
    <script src="/assets/js/bootstrap-dropdown.js"></script>
    <script src="/assets/js/bootstrap-scrollspy.js"></script>
    <script src="/assets/js/bootstrap-tab.js"></script>
    <script src="/assets/js/bootstrap-tooltip.js"></script>
    <script src="/assets/js/bootstrap-popover.js"></script>
    <script src="/assets/js/bootstrap-button.js"></script>
    <script src="/assets/js/bootstrap-collapse.js"></script>
    <script src="/assets/js/bootstrap-carousel.js"></script>
    <script src="/assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>

